/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class LaporanFrame extends javax.swing.JFrame {

    private String url = "jdbc:mysql://localhost:3306/2210010156_pbo2";
    private String username = "root";
    private String password = "";
    private Connection connection;
    public LaporanFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try {
            Driver myDriver = new com.mysql.jdbc.Driver();
            DriverManager.registerDriver(myDriver);
            connection = DriverManager.getConnection(url, username, password);
            System.out.println("Frame Berhasil Dengan Database");
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        judul_laporan_input = new javax.swing.JTextField();
        id_pelapor_input = new javax.swing.JTextField();
        isi_laporan_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        laporan_add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        laporan_edit = new javax.swing.JButton();
        laporan_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Isi Laporan");

        judul_laporan_input.setName("judul_laporan_input"); // NOI18N
        judul_laporan_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_laporan_inputActionPerformed(evt);
            }
        });

        id_pelapor_input.setName("id_pelapor_input"); // NOI18N
        id_pelapor_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelapor_inputActionPerformed(evt);
            }
        });

        isi_laporan_input.setName("isi_laporan_input"); // NOI18N
        isi_laporan_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_laporan_inputActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Frame Laporan");

        laporan_add.setText("Masukkan Data");
        laporan_add.setName("laporan_add"); // NOI18N
        laporan_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_addActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Pelapor");

        jLabel3.setText("Judul Laporan");

        laporan_edit.setText("Ubah Data");
        laporan_edit.setName("laporan_submit"); // NOI18N
        laporan_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_editActionPerformed(evt);
            }
        });

        laporan_delete.setText("Hapus Data");
        laporan_delete.setName("laporan_submit"); // NOI18N
        laporan_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laporan_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laporan_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(judul_laporan_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(isi_laporan_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(laporan_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul_laporan_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isi_laporan_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laporan_edit)
                    .addComponent(laporan_delete))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void judul_laporan_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_laporan_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_laporan_inputActionPerformed

    private void id_pelapor_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelapor_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelapor_inputActionPerformed

    private void isi_laporan_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_laporan_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_laporan_inputActionPerformed

    private void laporan_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_addActionPerformed
        try {
        String saveData = "insert into laporan (id_pelapor, judul_laporan, isi_laporan) values (?,?,?)";
        PreparedStatement primaryKeyCheck = connection.prepareStatement("select * from laporan where id_pelapor = ?");
        primaryKeyCheck.setString(1, id_pelapor_input.getText());
        
        ResultSet dataResult = primaryKeyCheck.executeQuery();
        
        if (dataResult.next()) {
            JOptionPane.showMessageDialog(null, "Kode Primary Key Sudah Terdaftar");
        } else {
            PreparedStatement saveQuery = connection.prepareStatement(saveData);
            saveQuery.setString(1, id_pelapor_input.getText());
            saveQuery.setString(2, judul_laporan_input.getText());
            saveQuery.setString(3, isi_laporan_input.getText());
            saveQuery.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        }
        // Menutup resource di dalam blok finally atau setelah selesai
        primaryKeyCheck.close();
        dataResult.close();
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_laporan_addActionPerformed

    private void laporan_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_editActionPerformed
        try {
        String checkSQL = "SELECT * FROM laporan WHERE id_pelapor = ?";
        PreparedStatement checkQuery = connection.prepareStatement(checkSQL);
        checkQuery.setString(1, id_pelapor_input.getText());

        ResultSet dataResult = checkQuery.executeQuery();

        if (dataResult.next()) {
            // Query untuk update data
            String updateSQL = "UPDATE laporan SET judul_laporan = ?, isi_laporan = ? WHERE id_pelapor = ?";
            PreparedStatement updateQuery = connection.prepareStatement(updateSQL);
            updateQuery.setString(1, judul_laporan_input.getText());
            updateQuery.setString(2, isi_laporan_input.getText());
            updateQuery.setString(3, id_pelapor_input.getText());
            updateQuery.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");

            updateQuery.close();
        } else {
            JOptionPane.showMessageDialog(null, "ID Pelapor tidak ditemukan");
        }

        checkQuery.close();
        dataResult.close();
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_laporan_editActionPerformed

    private void laporan_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_deleteActionPerformed
        try {
        String checkSQL = "SELECT * FROM laporan WHERE id_pelapor = ?";
        PreparedStatement checkQuery = connection.prepareStatement(checkSQL);
        checkQuery.setString(1, id_pelapor_input.getText());

        ResultSet dataResult = checkQuery.executeQuery();

        if (dataResult.next()) {
            // Query untuk menghapus data
            String deleteSQL = "DELETE FROM laporan WHERE id_pelapor = ?";
            PreparedStatement deleteQuery = connection.prepareStatement(deleteSQL);
            deleteQuery.setString(1, id_pelapor_input.getText());
            deleteQuery.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

            deleteQuery.close();
        } else {
            JOptionPane.showMessageDialog(null, "ID Pelapor tidak ditemukan");
        }

        checkQuery.close();
        dataResult.close();
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_laporan_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_pelapor_input;
    private javax.swing.JTextField isi_laporan_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField judul_laporan_input;
    private javax.swing.JButton laporan_add;
    private javax.swing.JButton laporan_delete;
    private javax.swing.JButton laporan_edit;
    // End of variables declaration//GEN-END:variables
}
