/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PelaporFrame extends javax.swing.JFrame {

    private String url = "jdbc:mysql://localhost:3306/2210010156_pbo2";
    private String username = "root";
    private String password = "";
    private Connection connection;
    
    public PelaporFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try {
            Driver myDriver = new com.mysql.jdbc.Driver();
            DriverManager.registerDriver(myDriver);
            connection = DriverManager.getConnection(url, username, password);
            System.out.println("Frame Berhasil Dengan Database");
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama_pelapor_input = new javax.swing.JTextField();
        id_pelapor_input = new javax.swing.JTextField();
        jk_input = new javax.swing.JTextField();
        telp_input = new javax.swing.JTextField();
        pelapor_add = new javax.swing.JButton();
        pelapor_delete = new javax.swing.JButton();
        pelapor_edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Frame Pelapor");

        jLabel2.setText("ID Pelapor");

        jLabel3.setText("Nama Pelapor");

        jLabel4.setText("No. Telp");

        jLabel5.setText("Jenis Kelamin");

        nama_pelapor_input.setName("nama_pelapor_input"); // NOI18N
        nama_pelapor_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pelapor_inputActionPerformed(evt);
            }
        });

        id_pelapor_input.setName("id_pelapor_input"); // NOI18N
        id_pelapor_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelapor_inputActionPerformed(evt);
            }
        });

        jk_input.setName("jk_input"); // NOI18N
        jk_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk_inputActionPerformed(evt);
            }
        });

        telp_input.setName("telp_pelapor_input"); // NOI18N
        telp_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telp_inputActionPerformed(evt);
            }
        });

        pelapor_add.setText("Masukkan Data");
        pelapor_add.setName("pelapor_add"); // NOI18N
        pelapor_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelapor_addActionPerformed(evt);
            }
        });

        pelapor_delete.setText("Hapus Data");
        pelapor_delete.setName("pelapor_add"); // NOI18N
        pelapor_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelapor_deleteActionPerformed(evt);
            }
        });

        pelapor_edit.setText("Ubah Data");
        pelapor_edit.setName("pelapor_add"); // NOI18N
        pelapor_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelapor_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nama_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telp_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jk_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(id_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(pelapor_add, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pelapor_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pelapor_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_pelapor_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telp_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelapor_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelapor_edit)
                    .addComponent(pelapor_delete))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_pelapor_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pelapor_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pelapor_inputActionPerformed

    private void id_pelapor_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelapor_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelapor_inputActionPerformed

    private void jk_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk_inputActionPerformed

    private void telp_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telp_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telp_inputActionPerformed

    private void pelapor_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelapor_addActionPerformed
        try {
        String saveData = "insert into pelapor (id_pelapor, nama, telp, jenis_kelamin) values (?,?,?,?)";
        PreparedStatement primaryKeyCheck = connection.prepareStatement("select * from pelapor where id_pelapor = ?");
        primaryKeyCheck.setString(1, id_pelapor_input.getText());
        
        ResultSet dataResult = primaryKeyCheck.executeQuery();
        
        if (dataResult.next()) {
            JOptionPane.showMessageDialog(null, "Kode Primary Key Sudah Terdaftar");
        } else {
            PreparedStatement saveQuery = connection.prepareStatement(saveData);
            saveQuery.setString(1, id_pelapor_input.getText());
            saveQuery.setString(2, nama_pelapor_input.getText());
            saveQuery.setString(3, telp_input.getText());
            saveQuery.setString(4, jk_input.getText());
            saveQuery.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        }

        // Menutup resource di dalam blok finally atau setelah selesai
        primaryKeyCheck.close();
        dataResult.close();
    } catch (Exception e) {
        System.err.println(e.toString());
    }
    }//GEN-LAST:event_pelapor_addActionPerformed

    private void pelapor_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelapor_deleteActionPerformed
        try {
            String deleteData = "DELETE FROM pelapor WHERE id_pelapor = ?";
            PreparedStatement deleteQuery = connection.prepareStatement(deleteData);

            deleteQuery.setString(1, id_pelapor_input.getText());

            int affectedRows = deleteQuery.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }

            deleteQuery.close();
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_pelapor_deleteActionPerformed

    private void pelapor_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelapor_editActionPerformed
        try {
            String updateData = "UPDATE pelapor SET nama = ?, telp = ?, jenis_kelamin = ? WHERE id_pelapor = ?";
            PreparedStatement updateQuery = connection.prepareStatement(updateData);

            updateQuery.setString(1, nama_pelapor_input.getText());
            updateQuery.setString(2, telp_input.getText());
            updateQuery.setString(3, jk_input.getText());
            updateQuery.setString(4, id_pelapor_input.getText());

            int affectedRows = updateQuery.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil Memperbarui Data");
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }

            updateQuery.close();
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_pelapor_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelaporFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelaporFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelaporFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelaporFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelaporFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_pelapor_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jk_input;
    private javax.swing.JTextField nama_pelapor_input;
    private javax.swing.JButton pelapor_add;
    private javax.swing.JButton pelapor_delete;
    private javax.swing.JButton pelapor_edit;
    private javax.swing.JTextField telp_input;
    // End of variables declaration//GEN-END:variables
}
